### ISSUE TITLE
Add CoarseGrid constructor from ABAQUS file

### ISSUE THREAD

**Issue by masonamccallum** [HorribleSanity/Raven.jl#39]
This will be useful for the geometries I plan to run on. The implementation seems simple however curved elements might require some additional work. A discussion about this might be useful.

**Comment by lcw** [comment]
This would be useful!  Curved elements will need some thought.  I don't know how they are represented in ABAQUS files.

**Comment by masonamccallum** [comment]
[This](https://trixi-framework.github.io/Trixi.jl/stable/meshes/p4est_mesh/) is how Trixi handles this. In short HOHQMesh appends the curved element CGL-interpolation points to an ABAQUS file as a comment. Im not sure how the points on the internal of an element would be placed.

**Comment by lcw** [comment]
It would be great if we could read HOHQMesh generated files.  Once we know how the edges/faces of the trees are warped, we can use transfinite blending [1] to come up with a separate mapping for each tree.

To use this per tree mapping, the warp function passed into `Raven.generate` would then need to take in an `x` and the tree-id. 

[1] Gordon, W.J., Hall, C.A. Transfinite element methods: Blending-function interpolation over arbitrary curved element domains. Numer. Math. 21, 109–129 (1973). https://doi.org/10.1007/BF01436298

**Comment by lcw** [comment]
It would be good to check the ordering of the elements generated by HOHQMesh as p4est partitions them simply based on their order.  Thus, it may be useful to order them using a space filling curve.  For this, something like https://github.com/CliMA/GilbertCurves.jl could be useful.

**Comment by lcw** [comment]
It looks like the trixi documentation discusses how the transfinite blending works in the hex case here <https://trixi-framework.github.io/Trixi.jl/stable/meshes/p4est_mesh/#Mesh-in-three-spatial-dimensions>.
